### ISSUE TITLE
Does it support SAML authentication on android

### ISSUE THREAD

**Issue by rskumar** [okta/oktasdk-java#2]
Can I use it to develop app with okta saml 2.0 sso? If not, please provide a right pointer where I can find examples and supported libraries.

**Comment by tbeech** [comment]
Not sure if this is too late, but after researching this a bit, I don't think SAML is a good fit for mobile due to the fact that it's primary purpose is to solve SSO for the browser. Okta does provide an API that allows you to authenticate the user via user login and password from there you can create an Okta session that you could use inside your app. You would have to integrate your app server side to do this. Look at the authentication and session APIs.

**Comment by joelfranusic-okta** [comment]
To close this off, @tbeech is correct here. SAML is not usually a good fit for mobile development mostly due to the effort required to get SAML working with a mobile browser. 

People looking to add SSO support to a mobile app in 2017 and beyond should look into implementing [OIDC, which Okta now supports](http://developer.okta.com/docs/api/resources/oidc.html) and is currently available as an Early Access feature.
